name: Remove old artifacts

on: [ workflow_dispatch, pull_request, push ]

jobs:
  remove-old-artifacts:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '10 minutes' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          skip-recent: 5